/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure '.'
  // To create sub folders for specific docs, write your subfolder name in dirName
  // sentinelSidebar: [{type: 'autogenerated', dirName: 'sentinelguides'}],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'sentinelguides/resources'}],
  nodeSidebar: [{type: 'autogenerated', dirName: 'sentinelguides/node'}],
  validatorSidebar: [{type: 'autogenerated', dirName: 'sentinelguides/validator'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
